# Datenstrom Yellow extension settings

Extension: Example
Version: 1.0.2
Description: Example feature for Datenstrom Yellow.
Developer: Anna Svensson
Contributor: Giovanni Salmeri, Mark Seuffert, Steffen Schultz
Tag: example, feature
DownloadUrl: https://github.com/datenstrom/yellow-example/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/datenstrom/yellow-example
Published: 2026-09-25 19:26:46
Status: experimental
system/workers/example.php: example.php, create, update
